type: symfony
docroot: public/
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
timezone: UTC
composer_version: "2"
web_environment: []
corepack_enable: false
webimage_extra_packages: ["php${DDEV_PHP_VERSION}-vips", "libvips", "libffi-dev"]
hooks:
    post-start:
        - exec: symfony run --daemon --watch=config,src,templates,vendor bin/console messenger:consume async -vv
